### ISSUE TITLE
Crashes after log in

### ISSUE THREAD

**Issue by frigon** [Telerik-Verified-Plugins/Facebook#1]
On ios8 with iphone 6.  Upon throwing back into my app, the spashscreen shows for several seconds then the app crashes.  That makes me sad.

**Comment by EddyVerbruggen** [comment]
That's unfortunate. Is this with [our demo app](https://github.com/Telerik-Verified-Plugins/Facebook-DemoApp)?

**Comment by frigon** [comment]
I suspect its something the plugin marketplace plugin conf settings.   If I clone from github it seems to work…but  the plugin shows as a subfolder in the plugins directory in that case.

I’ve just copied and pasted your scripts into the list project but it crashes…

-mark

**Comment by EddyVerbruggen** [comment]
Mark, can you elaborate on the steps to reproduce the crash please? Or share that crashing app with me if you can?

**Comment by frigon** [comment]
I just sent over the project code.   Since there is inter app flow its hard to debug… I all I can tell is that it crashes during the splashscreen of the pass back.

Attached is  video…

**Comment by EddyVerbruggen** [comment]
@frigon please email me directly at eddyverbruggen at gmail.com as this doesn't seem to work.
