### ISSUE TITLE
Doesn't build with Phonegap Build

### ISSUE THREAD

**Issue by benmcmaster** [Telerik-Verified-Plugins/Facebook#10]
The main branch of phonegap-facebook-plugin is not building with PGB. I would love to try this plugin out.

Is this plugin on NPM? I don't see it.

PGB recently added support to grab plugins directly from GitHub. http://phonegap.com/blog/2016/02/16/git-plugins/

Using:

```
<plugin spec="https://github.com/Telerik-Verified-Plugins/Facebook.git#v1.0.1.1" source="git">
        <param name="APP_ID" value="<%=Settings.facebook.app_id%>" />
        <param name="APP_NAME" value="<%=Settings.facebook.app_name%>" />
</plugin>
```

in my config.xml file. Getting the error:

Error - Plugin error (you probably need to remove plugin files from your app): //github.com/Telerik-Verified-Plugins/Facebook.git#v1.0.1.1 --var APP_ID=524549440394380 --var APP_NAME=myapp": Fetching plugin "https://github.com/Telerik-Verified-Plugins/Facebook.git" via git clone Failed to fetch plugin https://github.com/Telerik-Verified-Plugins/Facebook.git via git. Either there is a connection problems, or plugin spec is incorrect: Error: git: Command failed with exit code 1 Error output: error: pathspec 'v1.0.1.1' did not match any file(s) known to git.

Any suggestions? Thank you!

**Comment by EddyVerbruggen** [comment]
Hi, looks like you should remove the 'v' from the version number.

**Comment by benmcmaster** [comment]
Doh! You are a genius. It works like a charm. Thank you!

Any plans to put this on NPM?

**Comment by EddyVerbruggen** [comment]
Awesome!

Glad that pgb supports git repo's. We're not adding this to npm I think. 

Cheers,
Eddy

**Comment by dhatawesomedude** [comment]
@benmcmaster how do you pass in your plugin value like this "Settings.facebook.app_id"? I can't seem to get mine to work.

 I am using pgb and I have.

```
<plugin spec="https://github.com/Telerik-Verified-Plugins/Facebook#1.0.1.1" source="git">
<param name="APP_ID" value="899927372832932"/>
<param name="APP_NAME" value="sjekjew"/>
```

  </plugin>

and I get
`Error - One of your plugins requires a parameter: APP_ID, APP_NAME`

**Comment by benmcmaster** [comment]
```
<plugin spec="https://github.com/Telerik-Verified-Plugins/Facebook.git#1.0.1.1" source="git">
    <param name="APP_ID" value="12345678" />
    <param name="APP_NAME" value="AwesomeApp" />
</plugin>
```

Are you missing the closing `</plugin>` tag? @dhatawesomedude

**Comment by dhatawesomedude** [comment]
Hey @benmcmaster thanks. I wasn't missing anything. For some very strange reason, changing my plugin list sequence - listing this plugin before the [push notification plugin](https://github.com/Telerik-Verified-Plugins/PushNotification#3.2.0) in the config.xml fixed the issue.
