### ISSUE TITLE
Doesn't stack with Custom URL Scheme's url scheme

### ISSUE THREAD

**Issue by kaansoral** [Telerik-Verified-Plugins/Facebook#2]
Hi

I've been manually adding the fb url scheme for ios, https://github.com/EddyVerbruggen/Custom-URL-scheme gets the precedence, the fb url scheme is overwritten

I'm not sure whether the android app requires a fb url scheme, but it's missing in the android project too (I'm guessing android doesn't need it)

Anyway, I just wanted to report the issue, I remember reading about a bug that prevented the addition of multiple url schemes, don't know whether that's still the case

**Comment by EddyVerbruggen** [comment]
Yeah that's been an issue for a while now. And it was finally fixed 5 days ago! See https://issues.apache.org/jira/browse/CB-8007

The component is `cordova-lib` but there is no fix version, so I can't tell when it will be released.

**Comment by kaansoral** [comment]
Thanks for the update :)
