### ISSUE TITLE
Bug with iOS 10: update the the Facebook lastest SDK

### ISSUE THREAD

**Issue by Nightbr** [Telerik-Verified-Plugins/Facebook#26]
Hey, 
with the release of iOS 10, the Facebook Connect login is not working anymore...
I made some research and it just need to update the latest Facebook SDK (4.15.0) to fix the bug.
Thanks in advance to your great work! Hope it will be fixed soon.

Litterature:

> WIth iOS 10 beta 8 and the latest Facebook SDK it appears this issue has been resolved.
- https://forums.developer.apple.com/thread/50332
- http://stackoverflow.com/questions/38689631/how-to-use-facebook-ios-sdk-on-ios-10
- https://developers.facebook.com/docs/ios/change-log-4.x/

**Comment by Nightbr** [comment]
Hello, 
I haven't a Mac at my disposition right now but I will try to debug this from a vm throught the emulator... 
This bug is really critical because iOS 10 was released recently and we can't let our users with Facebook Login...
Is there any maintainer available to look at this please?

Thanks in advance!

**Comment by Nightbr** [comment]
Victory!!! \o/
I success to run an iPhone emulator on iOS 10 under my OSX VM and I had this error:

> Sep 15 17:32:08 MacBook-Pro-de-Admin Welp[2588]: Starting login
> Sep 15 17:32:08 MacBook-Pro-de-Admin Welp[2588]: **\* WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> Permissions should each be specified in separate string values in the array.

Pretty clear, I found my mistakes... I had this before

`facebookConnectPlugin.login(['email,user_friends,public_profile,user_birthday'], fbLoginSuccess , fbLoginError)`

And I fix the bug with this

`facebookConnectPlugin.login(['email','user_friends','public_profile','user_birthday'], fbLoginSuccess , fbLoginError)`

It is just weird that it not works ONLY on iOS 10.

Thanks for this plugins btw

**Comment by EddyVerbruggen** [comment]
@Nightbr that's relief, thanks for sharing!
