### ISSUE TITLE
I can not install Cordova toast plugin

### ISSUE THREAD

**Issue by auroraruggieri** [Telerik-Verified-Plugins/Facebook#33]
I can not install Cordovatoast plugin, I get the following error:

Running command - failed!

ERROR] Cordova encountered an error.
       You may get more insight by running the Cordova command above directly.

ERROR] An error occurred while running cordova plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git
       -... (exit code 1):

       Error: Failed to fetch plugin https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git via registry.
       Probably this is either a connection problem, or plugin spec is incorrect.
       Check your connection and plugin name/version/URL.
       Error: cmd: Command failed with exit code 1 Error output:
       npm ERR! exited with error code: 128

       npm ERR! A complete log of this run can be found in:
       npm ERR!     C:\Users\Aurora\AppData\Roaming\npm-cache\_logs\2017-07-06T08_22_04_912Z-debug.log

This are the debug file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git',
1 verbose cli   '--save' ]
2 info using npm@5.0.3
3 info using node@v8.1.0
4 verbose npm-session 454b1dc83236a861
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git exited with error code: 128
8 verbose stack Error: exited with error code: 128
8 verbose stack     at ChildProcess.onexit (C:\Program Files\nodejs\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
8 verbose stack     at emitTwo (events.js:125:13)
8 verbose stack     at ChildProcess.emit (events.js:213:7)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
9 verbose cwd C:\Users\Aurora\desktop\Coursera\Ionic\conFusion\node_modules
10 verbose Windows_NT 10.0.14393
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git" "--save"
12 verbose node v8.1.0
13 verbose npm  v5.0.3
14 error exited with error code: 128
15 verbose exit [ 1, true ]

**Comment by ThomsheerAhamed** [comment]
I had same problem, when I tried to install using 

   `cordova plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git`

So Tried

 ` cordova plugin add cordova-plugin-x-toast`

In my case it worked..

note : try removing plugin once and install it again
`>cordova plugin remove cordova-plugin-x-toast`
`>cordova plugin add cordova-plugin-x-toast`
