### ISSUE TITLE
Update SDK iOS and Android

### ISSUE THREAD

**Issue by thiagoamarante** [Telerik-Verified-Plugins/Facebook#4]
Could upgrade the SDK facebook iOS and Android for greater than version 4.0?

**Comment by thiagoamarante** [comment]
Apple's iOS 9 introduces many changes that will affect the Facebook integration of your app “Spotchat”. You will need to make changes to preserve app functionality and ensure the best possible experience for people who use your iOS 9 app. Read this blog post for more information.

Action items you will need to take:

Download the new SDK for iOS 4.6 or v3.24.
The iOS 9 rollout introduces a new feature called App Transport Security which will require you to whitelist Facebook domains in your app's plist.
Update your app's plist to handle the changes to canOpenURL described here, so that your app can open dialogs in the Facebook app (for Login, share, invite friends, or native Likes).
Submit the new version of your app to Apple's app store.
Please refer to this guide and changelog for more information.

**Comment by thiagoamarante** [comment]
{"errorCode":"4201","errorMessage":"User cancelled dialog"}
"Session: an attempt was made to request new permissions for a session that has a pending request."

Sometimes this message is returned when used in Android.

**Comment by EddyVerbruggen** [comment]
Hi @thiagoamarante, the upstream repo has a [PR](https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1051) which adds SDK 4+ support. I'm going to wait a bit for it to be merged so this repo stays mostly in sync with the upstream. It looks like it will be soon.

About ATS (App Transport Security): the Cordova guys are working on an [easy to use fix](https://issues.apache.org/jira/browse/CB-9569).

**Comment by juliencousineau** [comment]
Yes I'm looking forward this merge, AppInvite is a really important feature for app growth !

**Comment by VinceOPS** [comment]
I know this is not the good place for that but I just wanted to say "Thank you" so badly @EddyVerbruggen :+1: (for all your work and plugins).

By the way, +1 for app invite

**Comment by ashishsajwan** [comment]
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1063
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/985
is this issue resolved here ???

@thiagoamarante @EddyVerbruggen @aogilvie

**Comment by EddyVerbruggen** [comment]
Switched the upstream to the 'facebook4' plugin (you can't see it in GitHub, but we're now in sync with [this repo](https://github.com/jeduan/cordova-plugin-facebook4)).
