### ISSUE TITLE
Falling back to web auth

### ISSUE THREAD

**Issue by kaansoral** [Telerik-Verified-Plugins/Facebook#7]
Hi everyone,

I just tested this plugin and the new facebook4 fork of the origin-wizcorp-plugin, they both fall back to web auth for me, not a browser based hybrid auth either, a web auth where you have to re-enter your password

I just tested a very old version of the wizcorp plugin, that one still works, it just asks whether the user wants to open the facebook app

During this testing I used an iPod with the latest iOS and fb app

**Comment by kaansoral** [comment]
![img_1308](https://cloud.githubusercontent.com/assets/170243/11917289/3ee0ec06-a70a-11e5-8136-c01c24394ca5.jpg)

To clarify, this is what I get, both on an iPad and an iPod, don't know what changed, checking the plugin changes, it might be the build stuff that broke things for me

**Comment by stevecarlton** [comment]
I believe this is related to Facebook's new SDK and is unavoidable for iOS 9. The wizcorp plugin is likely using the old SDK.

I may be wrong but I have seen a few comments mentioning this.

**Comment by kaansoral** [comment]
Yes, this is a good read, especially the comments: https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9

Less people use external apps, facebook wins, more people login with safari, facebook wins, external developers waste time with this, facebook wins

I've tried using a pre fbv4.6 version of this plugin, but for some reason that didn't work either, at this point I will probably pull an earlier build from my time machine and see how things were working and how I didn't notice any issues before (Edit: I actually tested a pre fbv4.6 version of another fork, will try this one now)

To clarify, "Safari View Controller" shares auth with Safari.app and not Facebook.app, so users are only able to login friction-free if they logged in to facebook.com on Safari before, unlikely

Off topic, I've been developing facebook apps for more than 5 years, the pattern is clear, they hate external developers and do as much as they can get away with to hinder them stealthily, so if anyone reads this, it might be a good idea to just drop facebook integration and save yourself some time

**Comment by kaansoral** [comment]
As an update, this is the solution: https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1206

**Comment by EddyVerbruggen** [comment]
Thank you very much, that indeed explains a lot. I had to do something similar for the [Google login plugin](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/plugin.xml#L92-L102) a while ago.

Released this with 1.0.1.
