### ISSUE TITLE
Make post with graphCall

### ISSUE THREAD

**Issue by WamiConcept** [Telerik-Verified-Plugins/Facebook#8]
Hello, tank you for this plugin !

I want to make graphCall to publish post on facebook (without the dialog) the request must called with post method. How can I do this ?

Thanks

**Comment by WamiConcept** [comment]
I found .

we can do it with the parameters method.

```
facebookConnectPlugin.api(userid + '/feed?method=post&message=test&access_token=' + accessToken, ['publish_actions'], function(r){}, function(e){});
```

**Comment by Scalpweb** [comment]
Could you tell me how you asked for the "publish_actions" permissions ?

Thanks
