### ISSUE TITLE
Cordova 4 iOS issue

### ISSUE THREAD

**Issue by jonnylevy** [Telerik-Verified-Plugins/Facebook#9]
Hi,

I have been using this plugin without a problem for a while until today, when I updated my Cordova ios to 4.0.1. 

Now when I try to build my app in xcode I get the error:
`/Plugins/com.phonegap.plugins.facebookconnect/FacebookConnectPlugin.m:27:44: No visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'`

Any suggestions?

Thanks

**Comment by EddyVerbruggen** [comment]
For now use 3.x, but I will check it!

```
cordova platform remove ios
cordova platform add ios@3.9.2
```

**Comment by EddyVerbruggen** [comment]
1.0.1.1 fixes the issue for cordova-ios-4.

**Comment by jonnylevy** [comment]
Yup, works now. Thanks!
